<?php

/**
 * Novalnet payment module
 *
 * This file is used for the admin German language
 *
 * @author    Novalnet AG
 * @copyright Copyright by Novalnet
 * @link      https://www.novalnet.de
 * @license   https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 *
 * Script: novalnet_lang.php
 */

$sLangName = 'Deutsch';

$aLang = [
    'charset'                                           => 'UTF-8',
    'tabnovalnet_order'                                 => 'Novalnet',
    'SHOP_MODULE_GROUP_novalnetGlobalSettings'          => 'Novalnet API-Konfiguration',
    'SHOP_MODULE_sProductActivationKey'                 => 'Produktaktivierungsschlüssel',
    'HELP_SHOP_MODULE_sProductActivationKey'            => 'Ihr Produktaktivierungsschlüssel ist ein eindeutiger Token für die Händlerauthentifizierung und Zahlungsabwicklung.Ihr Produktaktivierungsschlüssel ist ein eindeutiges Token für die Händlerauthentifizierung und Zahlungsabwicklung. Ihren Produktaktivierungsschlüssel finden Sie im <a href="https://admin.novalnet.de" target="_blank" style="text-decoration: underline; font-weight: bold; color:#0080c9;"> Novalnet Admin-Portal </a>: Projekts > Wählen Sie Ihr Projekt > API-Anmeldeinformationen > API-Signatur (Produktaktivierungsschlüssel)',
    'SHOP_MODULE_sPaymentAccessKey'                     => ' Zahlungs-Zugriffsschlüssel',
    'HELP_SHOP_MODULE_sPaymentAccessKey'                => 'Ihren Paymentzugriffsschlüssel finden Sie im <a class="novalnet_config_link" href="https://admin.novalnet.de" target="_blank">Novalnet Admin-Portal</a> Projekts > Wählen Sie Ihr Projekt > API-Anmeldeinformationen > Paymentzugriffsschlüssel',
    'SHOP_MODULE_sTariffId'                             => ' Auswahl der Tarif-ID',
    'HELP_SHOP_MODULE_sTariffId'                        => 'Wählen Sie eine Tarif-ID, die dem bevorzugten Tarifplan entspricht, den Sie im <a class="novalnet_admin_link" href="https://admin.novalnet.de" target="_blank">Novalnet Admin-Portal</a> für dieses Projekt erstellt haben',
    'SHOP_MODULE_sTariffId_None'                        => 'None',
    'SHOP_MODULE_GROUP_novalnetGlobalSettingsWebhook'   => 'Benachrichtigungs- / Webhook-URL festlegen',
    'SHOP_MODULE_blWebhookNotification'                 => 'Manuelles Testen der Benachrichtigungs- / Webhook-URL erlauben',
    'HELP_SHOP_MODULE_blWebhookNotification'            => 'Aktivieren Sie diese Option, um die Novalnet-Benachrichtigungs-/Webhook-URL manuell zu testen. Deaktivieren Sie die Option, bevor Sie Ihren Shop liveschalten, um unautorisierte Zugriffe von Dritten zu blockieren',
    'SHOP_MODULE_blWebhookSendMail'                     => 'E-Mails senden an',
    'HELP_MODULE_blWebhookSendMail'                     => 'E-Mail-Benachrichtigungen werden an diese E-Mail-Adresse gesendet',
    'SHOP_MODULE_sWebhooksUrl'                          => 'Benachrichtigungs- / Webhook-URL',
    'HELP_SHOP_MODULE_sWebhooksUrl'                     => 'Eine Benachrichtigungs- / Webhook-URL ist erforderlich, um die Datenbank / das System des Händlers mit dem Novalnet-Account synchronisiert zu halten (z.B. Lieferstatus). Weitere Informationen finden Sie in der Installationsanleitung',
    'NOVALNET_CONFIRM_BOOKED'                           => 'Sind Sie sich sicher, dass Sie den Bestellbetrag buchen wollen?',
    'NOVALNET_PAYMENT_NOT'                              => 'Diese Registerkarte ist nur für novalnet-Bestellungen',
    'NOVALNET_INSTALMENT_SNO'                           => 'S.Nr.',
    'NOVALNET_INSTALMENT_TID'                           => 'Novalnet-Transaktions-ID:',
    'NOVALNET_INSTALMENT_DATE'                          => 'Datum',
    'NOVALNET_INSTALMENT_AMOUNT'                        => 'Betrag',
    'NOVALNET_INSTALMENT_NEXT_CYCLE'                    => 'Datum des nächsten Zyklus',
    'NOVALNET_INSTALMENT_STATUS'                        => 'Status',
    'NOVALNET_INSTALMENT_REFUND'                        => 'Rückerstattung der Rate',
    'NOVALNET_INSTALMENT_REFUND_ACTION'                 => 'Rückerstattung',
    'NOVALNET_INSTALMENT_REFUND_AMOUNT'                 => 'Rückerstattungsbetrag',
    'NOVALNET_INSTALMENT_REFUND_REASON'                 => 'Grund der Rückerstattung/Stornierung',
    'NOVALNET_INSTALMENT_REFUND_CONFIRM'                => 'Bestätigen',
    'NOVALNET_INSTALMENT_REFUND_CANCEL'                 => 'Stornieren',
    'NOVALNET_INSTALMENT_CANCEL_ALL_CYCLE'              => 'Gesamte Ratenzahlung stornieren',
    'NOVALNET_INSTALMENT_CANCEL_REMAINING_CYCLE'        => 'Alle übrigen Installationen abbrechen',
    'NOVALNET_INSTALMENT_CANCEL'                        => 'Ratenzahlung Stornieren',
    'NOVALNET_INSTALMENT_HEADER'                        => 'Ratenzahlungsbestellungen Details',
    'NOVALNET_AMOUNT_BOOKED_MESSAGE'                    => '<br><br>Ihre Bestellung wurde mit einem Betrag von %s gebucht. Ihre neue TID für den gebuchten Betrag: %s',
    'NOVALNET_BOOK_AMOUNT_TITLE'                        => 'Transaktion durchführen',
    'NOVALNET_BOOK_AMOUNT_LABEL'                        => 'Buchungsbetrag der Transaktion',
    'NOVALNET_MANAGE_TRANSACTION_TITLE'                 => 'Ablauf der Buchung steuern',
    'NOVALNET_MANAGE_TRANSACTION_LABEL'                 => 'Wählen Sie bitte einen Status aus',
    'NOVALNET_CONFIRM'                                  => 'Bestätigen',
    'NOVALNET_CANCEL'                                   => 'Stornieren',
    'NOVALNET_UPDATE'                                   => 'Ändern',
    'NOVALNET_UPDATE_AMOUNT_TITLE'                      => 'Betrag ändern',
    'NOVALNET_UPDATE_AMOUNT_LABEL'                      => 'Betrag der Transaktion ändern',
    'NOVALNET_CENTS'                                    => '(in der kleinsten Währungseinheit,<br> z.B. 100 Cent = entsprechen 1.00 EUR)',
    'NOVALNET_REFUND_AMOUNT_TITLE'                      => 'Ablauf der Rückerstattung',
    'NOVALNET_REFUND_AMOUNT_LABEL'                      => 'Geben Sie bitte den erstatteten Betrag ein',
    'NOVALNET_REFUND_REFERENCE_LABEL'                   => 'Grund der Rückerstattung/Stornierung',
    'NOVALNET_AMOUNT_REFUNDED_PARENT_TID_MESSAGE'       => '<br><br>Die Rückerstattung wurde für die TID: %s mit dem Betrag %s durchgeführt',
    'NOVALNET_AMOUNT_REFUNDED_CHILD_TID_MESSAGE'        => '. Ihre neue TID für den erstatteten Betrag: %s',
    'NOVALNET_STATUS_UPDATE_CONFIRMED_MESSAGE'          => '<br><br>Die Buchung wurde am %s um %s Uhr bestätigt <br>',
    'NOVALNET_STATUS_UPDATE_CANCELED_MESSAGE'           => '<br><br>Die Transaktion wurde am %s um %s Uhr storniert <br>',
    'NOVALNET_AMOUNT_UPDATED_MESSAGE'                   => '<br><br><br>Der Betrag der Transaktion %s wurde am %s um %s Uhr erfolgreich geändert',
    'NOVALNET_TRANSACTION_DETAILS'                      => 'Novalnet-Transaktionsdetails ',
    'NOVALNET_TRANSACTION_ID'                           => '<br>Novalnet Transaktions-ID: %s',
    'NOVALNET_TEST_ORDER'                               => '<br>Testbestellung<br>',
    'NOVALNET_UPDATE_AMOUNT_DUEDATE_TITLE'              => 'Betrag / Fälligkeitsdatum ändern',
    'NOVALNET_UPDATE_DUEDATE_LABEL'                     => 'Fälligkeitsdatum der Transaktion',
    'NOVALNET_DUE_DATE'                                 => 'Fälligkeitsdatum: ',
    'NOVALNET_ACCOUNT'                                  => '<br>Kontoinhaber: %s',
    'NOVALNET_AMOUNT'                                   => '<br>Betrag: %s',
    'NOVALNET_ORDER_NO'                                 => 'Bestellnummer ',
    'NOVALNET_INVALID_STATUS'                           => 'Wählen Sie bitte einen Status aus',
    'NOVALNET_INVALID_AMOUNT'                           => 'Ungültiger Betrag',
    'NOVALNET_INVALID_DUEDATE'                          => 'Ungültiges Fälligkeitsdatum',
    'NOVALNET_INVALID_PAST_DUEDATE'                     => 'Das Datum sollte in der Zukunft liegen',
    'NOVALNET_CONFIRM_CAPTURE'                          => 'Sind Sie sicher, dass Sie die Zahlung einziehen möchten?',
    'NOVALNET_CONFIRM_CANCEL'                           => 'Sind Sie sicher, dass Sie die Zahlung stornieren wollen?',
    'NOVALNET_CONFIRM_AMOUNT_UPDATE'                    => 'Sind Sie sich sicher, dass Sie den Bestellbetrag ändern wollen?',
    'NOVALNET_CONFIRM_DUEDATE_UPDATE'                   => 'Sind Sie sich sicher, dass Sie den Betrag / das Fälligkeitsdatum der Bestellung ändern wollen?',
    'NOVALNET_CONFIRM_REFUND'                           => 'Sind Sie sicher, dass Sie den Betrag zurückerstatten möchten?',
    'NOVALNET_AMOUNT_DATE_UPDATED_MESSAGE'              => '<br><br>Die Transaktion wurde mit dem Betrag %s und dem Fälligkeitsdatum %s aktualisiert.',
    'NOVALNET_CALLBACK_INSTALMENT_MESSAGE'              => '<br><br>Für die Transaktions-ID ist eine neue Rate eingegangen: %s . Die Transaktions-ID der neuen Rate lautet: %s mit Betrag %s am %s.',
    'NOVALNET_CALLBACK_INSTALMENT_CANCEL_MESSAGE'       => '<br><br>Die Ratenzahlung für die TID wurde gekündigt: %s am %s.',
    'NOVALNET_PAYMENT_REMAINTER1_MESSAGE'               => '<br><br>Zahlungserinnerung 1 wurde an den Kunden gesendet.',
    'NOVALNET_PAYMENT_REMAINTER2_MESSAGE'               => '<br><br>Zahlungserinnerung 2 wurde an den Kunden gesendet.',
    'NOVALNET_COLLECTION_AGENCY_MESSAGE'                => '<br><br>Die Transaktion wurde an das Inkassobüro übergeben. Inkasso-Referenz: %s',
    'NOVALNET_INVOICE_BANK_DESC'                        => '<br>Bitte überweisen Sie den Betrag von %1$s auf das folgende Konto',
    'NOVALNET_INSTALMENT_INVOICE_BANK_DESC'             => '<br>Bitte überweisen Sie den anzahl der raten %1$s auf das folgende Konto.',
    'NOVALNET_INVOICE_BANK_DESC_WITH_DUE'               => '<br>Bitte überweisen Sie den Betrag von %1$s spätestens bis zum %2$s auf das folgende Konto',
    'NOVALNET_INSTALMENT_INVOICE_BANK_DESC_WITH_DUE'    => '<br>Bitte überweisen Sie den Betrag von %1$s spätestens bis zum %2$s auf das folgende Konto',
    'NOVALNET_CALLBACK_UPDATE_STATUS_ONHOLD'            => '<br><br>Der Status der Transaktion mit der TID: %s wurde am %s Uhr von ausstehend auf ausgesetzt geändert',
    'NOVALNET_CALLBACK_UPDATE_STATUS_UPDATE'            => '<br><br>Die Transaktion wurde erfolgreich für die TID %s auf %s aktualisiert.',
    'NOVALNET_CALLBACK_UPDATE_DUEDATE'                  => '<br><br>Transaktion erfolgreich aktualisiert für die TID %s mit Betrag %s und Fälligkeitsdatum %s',
    'NOVALNET_CALLBACK_UPDATE_AMOUNT'                   => '<br><br>Transaktion erfolgreich aktualisiert für die TID %s mit Betrag %s',
    'NOVALNET_CALLBACK_CREDIT'                          => '<br><br>Die Gutschrift für die TID: %s in Höhe von wurde erfolgreich erhalten %s am %s. Neue TID: %s für die Gutschrift.',
    'NOVALNET_CALLBACK_CHARGEBACK'                      => '<br><br>Chargeback erfolgreich importiert für die TID: %1$s Betrag: %2$s am %3$s Uhr. TID der Folgebuchung: %4$s.',
    'NOVALNET_CALLBACK_REFUND_TEXT'                     => '<br><br>Die Rückerstattung für die TID: %s mit dem Betrag %s wurde veranlasst',
    'NOVALNET_CALLBACK_REFUND_TID_TEXT'                 => '<br><br>Die Rückerstattung für die TID: %s mit dem Betrag %s wurde veranlasst. Die neue TID für den erstatteten Betrag lautet: %s',
    'NOVALNET_IBAN'                                     => '<br>IBAN: %s',
    'NOVALNET_BIC'                                      => '<br>BIC: %s',
    'NOVALNET_BANK'                                     => '<br>Bank: %s %s',
    'NOVALNET_PLACE'                                    => '<br>Ort: %s',
    'NOVALNET_PAYMENT_REFERENCE_1'                      => '<br>Zahlungsreferenz : %s',
    'NOVALNET_PAYMENT_QR_CODE_REFERENCE'                => '<br><br>Alternativ können Sie auch den nachstehenden QR-Code verwenden, um die Zahlung zu erleichtern. Bitte scannen Sie ihn mit Ihrer Banking-App, um die Zahlung abzuschließen.',
    'NOVALNET_PAYMENT_QR_CODE_IMAGE'                    => '<br><div style="display: inline-block;"><img src="%s" alt="QR Code" title="QR Code"/></div>',
    'NOVALNET_ZERO_BOOKING_TEXT'                        => '<br>Diese Transaktion wird mit Nullbuchung bearbeitet',
    'NOVALNET_TEST_MODE_MESSAGE'                        => 'Die Zahlung wird im Testmodus durchgeführt, daher wird der Betrag für diese Transaktion nicht eingezogen.',
    'NOVALNET_PAYMENT_TYPE'                             => 'Bezahlung mit',
    'NOVALNET_INVOICE_COMMENTS_TITLE'                   => '<br><br>Überweisen Sie bitte den Betrag an die unten aufgeführte Bankverbindung unseres Zahlungsdienstleisters Novalnet<br>',
    'NOVALNET_INVOICE_MULTI_REF_DESCRIPTION'            => '<br>Bitte verwenden Sie die folgende Referenz als Zahlungsreferenz, da nur so Ihre Zahlung der Bestellung zugeordnet werden kann:',
    'NOVALNET_CHECK_HASH_FAILED_ERROR'                  => 'Während der Umleitung wurden einige Daten geändert. Die Überprüfung des Hashes schlug fehl',
    'NOVALNET_PLEASE_SELECT'                            => '--Auswählen--',
    'NOVALNET_DEFAULT_ERROR_MESSAGE'                    => 'Die Zahlung war nicht erfolgreich. Ein Fehler trat auf',
    'NOVALNET_INVALID_NAME_EMAIL'                       => 'Ungültige Werte für die Felder Kundenname-/email',
    'NOVALNET_MULTIBANCO_TEXT'                          => '<br>Bitte verwenden Sie die folgende Zahlungsreferenz, um den Betrag von %s an einem Multibanco-Geldautomaten oder über Ihr Onlinebanking zu bezahlen.',
    'NOVALNET_MULTIBANCO_PARTNER_REFERENCE'             => '<br>Partner-Zahlungsreferenz: %s',
    'NOVALNET_MULTIBANCO_PAYMENT_ENTITY_REFERENCE'      => '<br>Entität: %s',
    'NOVALNET_INVOICE_PENDING_TEXT'                     => '<br>Ihre Bestellung wird überprüft. Nach der Bestätigung senden wir Ihnen unsere Bankverbindung, an die Sie bitte den Gesamtbetrag der Bestellung überweisen. Bitte beachten Sie, dass dies bis zu 24 Stunden dauern kann',
    'NOVALNET_SEPA_PENDING_TEXT'                        => '<br>Ihre Bestellung wird derzeit überprüft. Wir werden Sie in Kürze über den Bestellstatus informieren. Bitte beachten Sie, dass dies bis zu 24 Stunden dauern kann.',
    'PAYMENT_METHOD'                                    => 'Zahlungsmethode',
    'GENERAL'                                           => '%s',
    'NOVALNET_PAYMENT_FAILED'                           => '<br>Zahlung fehlgeschlagen %s',
    'NOVALNET_MANDATORY_ERROR'                          => 'Bitte füllen Sie die erforderlichen Felder aus',
    'NOVALNET_WEBHOOK_SUCCESS_TEXT'                     => 'Callbackskript-/ Webhook-URL wurde erfolgreich im Novalnet Admin Portal konfiguriert',
    'NOVALNET_GOOGLEPAY_DESC'                           => '<br>Ihre Bestellung wurde erfolgreich mit Google Pay durchgeführt (%s **** %s)<br>',
    'NOVALNET_APPLEPAY_DESC'                            => '<br>Ihre Bestellung wurde erfolgreich mit Apple Pay durchgeführt (%s **** %s)<br>',
    'NOVALNET_INSTALMENT_REMAINING_CANCEL_MESSAGE'      => '<br><br>Die Ratenzahlung für die TID wurde gestoppt: %s um %s',
    'NOVALNET_INSTALMENT_STATUS_COMPLETED'              => 'Abgeschlossen',
    'NOVALNET_INSTALMENT_STATUS_PENDING'                => 'Ausstehend',
    'NOVALNET_INSTALMENT_STATUS_CANCELLED'              => 'Storniert',
    'NOVALNET_INSTALMENT_STATUS_REFUNDED'               => 'Erstattet',
    'INSTALMENT_CANCEL_ALL_ALERT'                       => 'Sind Sie sicher, dass Sie alle Zyklen abbrechen wollen?',
    'INSTALMENT_REMAINING_ALL_ALERT'                    => 'Sind Sie sicher, dass Sie die verbleibende Rate stornieren möchten?',
];
